#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master

#---------------------------------#
#  Environment Variables          #
#---------------------------------#
environment:
  MYGET_MASTER_API_KEY:
    secure: axghMNZVsrPcsVZU/HkSmkhpr10hDiUK5PGIRwX9+u4JdT1lytd1HnKcT7RK7w6n
  MYGET_DEVELOP_API_KEY:
    secure: TqJUXeQRUgm/bHZZuFvRbY8UP2SKqTHS6K8k22bdR8iLnJOhBQJNTNxUA86r+O0h
  MYGET_MASTER_SOURCE: https://www.myget.org/F/packages_master/
  MYGET_DEVELOP_SOURCE: https://www.myget.org/F/packages_develop/
  NUGET_API_KEY:
    secure: a/xbTgIAc+QGdAwANmenmrUJFG5hqB+jMyqB6y80KZYXfRHOVEB+1dB4CEyDednf
  NUGET_SOURCE: https://nuget.org/

#---------------------------------#
#  Notifications Configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/a21963d3bba4db60a63a
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- Tools -> Tools\packages.config

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /(doc).*/