//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("ReSharperReports")]
[assembly: AssemblyDescription("Command line tool to allow generation of human readable ReSharper Reports")]
[assembly: AssemblyCompany("gep13")]
[assembly: AssemblyProduct("ReSharperReports")]
[assembly: AssemblyVersion("0.2.0")]
[assembly: AssemblyFileVersion("0.2.0")]
[assembly: AssemblyInformationalVersion("0.2.0")]
[assembly: AssemblyCopyright("Copyright © gep13 and Contributors 2015 - Present")]
[assembly: CLSCompliant(true)]

