//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("ReSharperReports")]
[assembly: AssemblyDescription("ReSharperReports Console Application")]
[assembly: AssemblyCompany("gep13")]
[assembly: AssemblyProduct("ReSharperReports")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright © gep13 2015 - Present")]
[assembly: CLSCompliant(true)]

